### ISSUE TITLE
Case: path to METADATA not provided is not handled

### ISSUE THREAD

**Issue by prajwaltr93** [OpenBookPublishers/chapter-splitter#11]
Hi,

option `-m METADATA` is said to be optional
![image](https://user-images.githubusercontent.com/37269899/166191548-ceef3310-b2c4-4dd8-8146-35adaea0de69.png)

but, when it is treated as such, following error is shown,
![image](https://user-images.githubusercontent.com/37269899/166191634-4e3d7d84-6eb8-4c5d-aecf-9eff746d7b00.png)

Environment:
Python 3.8
Ubuntu 20.04 WSL

**Comment by prajwaltr93** [comment]
metadata is a json file with "isbn" as key:
`
{
  "isbn" : "<book's isbn>"
}
`
can this information be added in README ? and make METADATA argument compulsory in output of `--help` command.

**Comment by lb803** [comment]
Hi @prajwaltr93 , thanks for your input.
I rephrased the README to make it more clear; I am putting off the task on the input argument as this tool needs to undergo some maintenance in the next few months.
