### ISSUE TITLE
Remove OBP specific DOI structure

### ISSUE THREAD

**Issue by ja573** [OpenBookPublishers/chapter-splitter#2]
The code currently makes assumptions about how DOIs are structured, beyond the official definition (e.g. chapter DOIs are a subset of the book's).

**Comment by lb803** [comment]
[This commit](https://github.com/OpenBookPublishers/chapter-splitter/commit/034cda136bfe94dd05b2151d9a9112c98d1d447b) should have fixed that. @ja573  Do you think there is something else I should address?

**Comment by lb803** [comment]
OK, we definitely fixed this with [this commit](https://github.com/OpenBookPublishers/chapter-splitter/commit/350b57b1ae0ec09c74538ca87812667d587c313b).
